output                  = "app/models"
wipe                    = true
no-tests                = true
no-hooks                = true
add-global-variants     = true
no-context              = true

[mysql]
  dbname  = "test"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "root"
  sslmode = "false"
  blacklist = ["migrations", "other"]