// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Airport is an object representing the database table.
type Airport struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Code      string    `boil:"code" json:"code" toml:"code" yaml:"code"`
	CountryID int       `boil:"country_id" json:"country_id" toml:"country_id" yaml:"country_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *airportR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L airportL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AirportColumns = struct {
	ID        string
	Code      string
	CountryID string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Code:      "code",
	CountryID: "country_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AirportWhere = struct {
	ID        whereHelperint
	Code      whereHelperstring
	CountryID whereHelperint
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`airports`.`id`"},
	Code:      whereHelperstring{field: "`airports`.`code`"},
	CountryID: whereHelperint{field: "`airports`.`country_id`"},
	CreatedAt: whereHelpertime_Time{field: "`airports`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`airports`.`updated_at`"},
}

// AirportRels is where relationship names are stored.
var AirportRels = struct {
	Country            string
	OriginFlights      string
	DestinationFlights string
	HomeAirportJets    string
}{
	Country:            "Country",
	OriginFlights:      "OriginFlights",
	DestinationFlights: "DestinationFlights",
	HomeAirportJets:    "HomeAirportJets",
}

// airportR is where relationships are stored.
type airportR struct {
	Country            *Country    `boil:"Country" json:"Country" toml:"Country" yaml:"Country"`
	OriginFlights      FlightSlice `boil:"OriginFlights" json:"OriginFlights" toml:"OriginFlights" yaml:"OriginFlights"`
	DestinationFlights FlightSlice `boil:"DestinationFlights" json:"DestinationFlights" toml:"DestinationFlights" yaml:"DestinationFlights"`
	HomeAirportJets    JetSlice    `boil:"HomeAirportJets" json:"HomeAirportJets" toml:"HomeAirportJets" yaml:"HomeAirportJets"`
}

// NewStruct creates a new relationship struct
func (*airportR) NewStruct() *airportR {
	return &airportR{}
}

// airportL is where Load methods for each relationship are stored.
type airportL struct{}

var (
	airportAllColumns            = []string{"id", "code", "country_id", "created_at", "updated_at"}
	airportColumnsWithoutDefault = []string{"code", "country_id"}
	airportColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	airportPrimaryKeyColumns     = []string{"id"}
)

type (
	// AirportSlice is an alias for a slice of pointers to Airport.
	// This should generally be used opposed to []Airport.
	AirportSlice []*Airport

	airportQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	airportType                 = reflect.TypeOf(&Airport{})
	airportMapping              = queries.MakeStructMapping(airportType)
	airportPrimaryKeyMapping, _ = queries.BindMapping(airportType, airportMapping, airportPrimaryKeyColumns)
	airportInsertCacheMut       sync.RWMutex
	airportInsertCache          = make(map[string]insertCache)
	airportUpdateCacheMut       sync.RWMutex
	airportUpdateCache          = make(map[string]updateCache)
	airportUpsertCacheMut       sync.RWMutex
	airportUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single airport record from the query using the global executor.
func (q airportQuery) OneG() (*Airport, error) {
	return q.One(boil.GetDB())
}

// One returns a single airport record from the query.
func (q airportQuery) One(exec boil.Executor) (*Airport, error) {
	o := &Airport{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for airports")
	}

	return o, nil
}

// AllG returns all Airport records from the query using the global executor.
func (q airportQuery) AllG() (AirportSlice, error) {
	return q.All(boil.GetDB())
}

// All returns all Airport records from the query.
func (q airportQuery) All(exec boil.Executor) (AirportSlice, error) {
	var o []*Airport

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Airport slice")
	}

	return o, nil
}

// CountG returns the count of all Airport records in the query, and panics on error.
func (q airportQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// Count returns the count of all Airport records in the query.
func (q airportQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count airports rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q airportQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// Exists checks if the row exists in the table.
func (q airportQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if airports exists")
	}

	return count > 0, nil
}

// Country pointed to by the foreign key.
func (o *Airport) Country(mods ...qm.QueryMod) countryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.CountryID),
	}

	queryMods = append(queryMods, mods...)

	query := Countries(queryMods...)
	queries.SetFrom(query.Query, "`countries`")

	return query
}

// OriginFlights retrieves all the flight's Flights with an executor via origin_id column.
func (o *Airport) OriginFlights(mods ...qm.QueryMod) flightQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`flights`.`origin_id`=?", o.ID),
	)

	query := Flights(queryMods...)
	queries.SetFrom(query.Query, "`flights`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`flights`.*"})
	}

	return query
}

// DestinationFlights retrieves all the flight's Flights with an executor via destination_id column.
func (o *Airport) DestinationFlights(mods ...qm.QueryMod) flightQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`flights`.`destination_id`=?", o.ID),
	)

	query := Flights(queryMods...)
	queries.SetFrom(query.Query, "`flights`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`flights`.*"})
	}

	return query
}

// HomeAirportJets retrieves all the jet's Jets with an executor via home_airport_id column.
func (o *Airport) HomeAirportJets(mods ...qm.QueryMod) jetQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`jets`.`home_airport_id`=?", o.ID),
	)

	query := Jets(queryMods...)
	queries.SetFrom(query.Query, "`jets`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`jets`.*"})
	}

	return query
}

// LoadCountry allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (airportL) LoadCountry(e boil.Executor, singular bool, maybeAirport interface{}, mods queries.Applicator) error {
	var slice []*Airport
	var object *Airport

	if singular {
		object = maybeAirport.(*Airport)
	} else {
		slice = *maybeAirport.(*[]*Airport)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &airportR{}
		}
		args = append(args, object.CountryID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &airportR{}
			}

			for _, a := range args {
				if a == obj.CountryID {
					continue Outer
				}
			}

			args = append(args, obj.CountryID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`countries`),
		qm.WhereIn(`countries.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Country")
	}

	var resultSlice []*Country
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Country")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for countries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for countries")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Country = foreign
		if foreign.R == nil {
			foreign.R = &countryR{}
		}
		foreign.R.Airports = append(foreign.R.Airports, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CountryID == foreign.ID {
				local.R.Country = foreign
				if foreign.R == nil {
					foreign.R = &countryR{}
				}
				foreign.R.Airports = append(foreign.R.Airports, local)
				break
			}
		}
	}

	return nil
}

// LoadOriginFlights allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (airportL) LoadOriginFlights(e boil.Executor, singular bool, maybeAirport interface{}, mods queries.Applicator) error {
	var slice []*Airport
	var object *Airport

	if singular {
		object = maybeAirport.(*Airport)
	} else {
		slice = *maybeAirport.(*[]*Airport)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &airportR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &airportR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`flights`),
		qm.WhereIn(`flights.origin_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load flights")
	}

	var resultSlice []*Flight
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice flights")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on flights")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for flights")
	}

	if singular {
		object.R.OriginFlights = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &flightR{}
			}
			foreign.R.Origin = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.OriginID {
				local.R.OriginFlights = append(local.R.OriginFlights, foreign)
				if foreign.R == nil {
					foreign.R = &flightR{}
				}
				foreign.R.Origin = local
				break
			}
		}
	}

	return nil
}

// LoadDestinationFlights allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (airportL) LoadDestinationFlights(e boil.Executor, singular bool, maybeAirport interface{}, mods queries.Applicator) error {
	var slice []*Airport
	var object *Airport

	if singular {
		object = maybeAirport.(*Airport)
	} else {
		slice = *maybeAirport.(*[]*Airport)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &airportR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &airportR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`flights`),
		qm.WhereIn(`flights.destination_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load flights")
	}

	var resultSlice []*Flight
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice flights")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on flights")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for flights")
	}

	if singular {
		object.R.DestinationFlights = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &flightR{}
			}
			foreign.R.Destination = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.DestinationID {
				local.R.DestinationFlights = append(local.R.DestinationFlights, foreign)
				if foreign.R == nil {
					foreign.R = &flightR{}
				}
				foreign.R.Destination = local
				break
			}
		}
	}

	return nil
}

// LoadHomeAirportJets allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (airportL) LoadHomeAirportJets(e boil.Executor, singular bool, maybeAirport interface{}, mods queries.Applicator) error {
	var slice []*Airport
	var object *Airport

	if singular {
		object = maybeAirport.(*Airport)
	} else {
		slice = *maybeAirport.(*[]*Airport)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &airportR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &airportR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`jets`),
		qm.WhereIn(`jets.home_airport_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load jets")
	}

	var resultSlice []*Jet
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice jets")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on jets")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for jets")
	}

	if singular {
		object.R.HomeAirportJets = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &jetR{}
			}
			foreign.R.HomeAirport = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.HomeAirportID) {
				local.R.HomeAirportJets = append(local.R.HomeAirportJets, foreign)
				if foreign.R == nil {
					foreign.R = &jetR{}
				}
				foreign.R.HomeAirport = local
				break
			}
		}
	}

	return nil
}

// SetCountryG of the airport to the related item.
// Sets o.R.Country to related.
// Adds o to related.R.Airports.
// Uses the global database handle.
func (o *Airport) SetCountryG(insert bool, related *Country) error {
	return o.SetCountry(boil.GetDB(), insert, related)
}

// SetCountry of the airport to the related item.
// Sets o.R.Country to related.
// Adds o to related.R.Airports.
func (o *Airport) SetCountry(exec boil.Executor, insert bool, related *Country) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `airports` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"country_id"}),
		strmangle.WhereClause("`", "`", 0, airportPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CountryID = related.ID
	if o.R == nil {
		o.R = &airportR{
			Country: related,
		}
	} else {
		o.R.Country = related
	}

	if related.R == nil {
		related.R = &countryR{
			Airports: AirportSlice{o},
		}
	} else {
		related.R.Airports = append(related.R.Airports, o)
	}

	return nil
}

// AddOriginFlightsG adds the given related objects to the existing relationships
// of the airport, optionally inserting them as new records.
// Appends related to o.R.OriginFlights.
// Sets related.R.Origin appropriately.
// Uses the global database handle.
func (o *Airport) AddOriginFlightsG(insert bool, related ...*Flight) error {
	return o.AddOriginFlights(boil.GetDB(), insert, related...)
}

// AddOriginFlights adds the given related objects to the existing relationships
// of the airport, optionally inserting them as new records.
// Appends related to o.R.OriginFlights.
// Sets related.R.Origin appropriately.
func (o *Airport) AddOriginFlights(exec boil.Executor, insert bool, related ...*Flight) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.OriginID = o.ID
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `flights` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"origin_id"}),
				strmangle.WhereClause("`", "`", 0, flightPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.OriginID = o.ID
		}
	}

	if o.R == nil {
		o.R = &airportR{
			OriginFlights: related,
		}
	} else {
		o.R.OriginFlights = append(o.R.OriginFlights, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &flightR{
				Origin: o,
			}
		} else {
			rel.R.Origin = o
		}
	}
	return nil
}

// AddDestinationFlightsG adds the given related objects to the existing relationships
// of the airport, optionally inserting them as new records.
// Appends related to o.R.DestinationFlights.
// Sets related.R.Destination appropriately.
// Uses the global database handle.
func (o *Airport) AddDestinationFlightsG(insert bool, related ...*Flight) error {
	return o.AddDestinationFlights(boil.GetDB(), insert, related...)
}

// AddDestinationFlights adds the given related objects to the existing relationships
// of the airport, optionally inserting them as new records.
// Appends related to o.R.DestinationFlights.
// Sets related.R.Destination appropriately.
func (o *Airport) AddDestinationFlights(exec boil.Executor, insert bool, related ...*Flight) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.DestinationID = o.ID
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `flights` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"destination_id"}),
				strmangle.WhereClause("`", "`", 0, flightPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.DestinationID = o.ID
		}
	}

	if o.R == nil {
		o.R = &airportR{
			DestinationFlights: related,
		}
	} else {
		o.R.DestinationFlights = append(o.R.DestinationFlights, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &flightR{
				Destination: o,
			}
		} else {
			rel.R.Destination = o
		}
	}
	return nil
}

// AddHomeAirportJetsG adds the given related objects to the existing relationships
// of the airport, optionally inserting them as new records.
// Appends related to o.R.HomeAirportJets.
// Sets related.R.HomeAirport appropriately.
// Uses the global database handle.
func (o *Airport) AddHomeAirportJetsG(insert bool, related ...*Jet) error {
	return o.AddHomeAirportJets(boil.GetDB(), insert, related...)
}

// AddHomeAirportJets adds the given related objects to the existing relationships
// of the airport, optionally inserting them as new records.
// Appends related to o.R.HomeAirportJets.
// Sets related.R.HomeAirport appropriately.
func (o *Airport) AddHomeAirportJets(exec boil.Executor, insert bool, related ...*Jet) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.HomeAirportID, o.ID)
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `jets` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"home_airport_id"}),
				strmangle.WhereClause("`", "`", 0, jetPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.HomeAirportID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &airportR{
			HomeAirportJets: related,
		}
	} else {
		o.R.HomeAirportJets = append(o.R.HomeAirportJets, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &jetR{
				HomeAirport: o,
			}
		} else {
			rel.R.HomeAirport = o
		}
	}
	return nil
}

// SetHomeAirportJetsG removes all previously related items of the
// airport replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.HomeAirport's HomeAirportJets accordingly.
// Replaces o.R.HomeAirportJets with related.
// Sets related.R.HomeAirport's HomeAirportJets accordingly.
// Uses the global database handle.
func (o *Airport) SetHomeAirportJetsG(insert bool, related ...*Jet) error {
	return o.SetHomeAirportJets(boil.GetDB(), insert, related...)
}

// SetHomeAirportJets removes all previously related items of the
// airport replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.HomeAirport's HomeAirportJets accordingly.
// Replaces o.R.HomeAirportJets with related.
// Sets related.R.HomeAirport's HomeAirportJets accordingly.
func (o *Airport) SetHomeAirportJets(exec boil.Executor, insert bool, related ...*Jet) error {
	query := "update `jets` set `home_airport_id` = null where `home_airport_id` = ?"
	values := []interface{}{o.ID}
	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	_, err := exec.Exec(query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.HomeAirportJets {
			queries.SetScanner(&rel.HomeAirportID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.HomeAirport = nil
		}

		o.R.HomeAirportJets = nil
	}
	return o.AddHomeAirportJets(exec, insert, related...)
}

// RemoveHomeAirportJetsG relationships from objects passed in.
// Removes related items from R.HomeAirportJets (uses pointer comparison, removal does not keep order)
// Sets related.R.HomeAirport.
// Uses the global database handle.
func (o *Airport) RemoveHomeAirportJetsG(related ...*Jet) error {
	return o.RemoveHomeAirportJets(boil.GetDB(), related...)
}

// RemoveHomeAirportJets relationships from objects passed in.
// Removes related items from R.HomeAirportJets (uses pointer comparison, removal does not keep order)
// Sets related.R.HomeAirport.
func (o *Airport) RemoveHomeAirportJets(exec boil.Executor, related ...*Jet) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.HomeAirportID, nil)
		if rel.R != nil {
			rel.R.HomeAirport = nil
		}
		if _, err = rel.Update(exec, boil.Whitelist("home_airport_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.HomeAirportJets {
			if rel != ri {
				continue
			}

			ln := len(o.R.HomeAirportJets)
			if ln > 1 && i < ln-1 {
				o.R.HomeAirportJets[i] = o.R.HomeAirportJets[ln-1]
			}
			o.R.HomeAirportJets = o.R.HomeAirportJets[:ln-1]
			break
		}
	}

	return nil
}

// Airports retrieves all the records using an executor.
func Airports(mods ...qm.QueryMod) airportQuery {
	mods = append(mods, qm.From("`airports`"))
	return airportQuery{NewQuery(mods...)}
}

// FindAirportG retrieves a single record by ID.
func FindAirportG(iD int, selectCols ...string) (*Airport, error) {
	return FindAirport(boil.GetDB(), iD, selectCols...)
}

// FindAirport retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAirport(exec boil.Executor, iD int, selectCols ...string) (*Airport, error) {
	airportObj := &Airport{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `airports` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, airportObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from airports")
	}

	return airportObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Airport) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Airport) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no airports provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(airportColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	airportInsertCacheMut.RLock()
	cache, cached := airportInsertCache[key]
	airportInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			airportAllColumns,
			airportColumnsWithDefault,
			airportColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(airportType, airportMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(airportType, airportMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `airports` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `airports` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `airports` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, airportPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into airports")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == airportMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}
	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for airports")
	}

CacheNoHooks:
	if !cached {
		airportInsertCacheMut.Lock()
		airportInsertCache[key] = cache
		airportInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single Airport record using the global executor.
// See Update for more documentation.
func (o *Airport) UpdateG(columns boil.Columns) (int64, error) {
	return o.Update(boil.GetDB(), columns)
}

// Update uses an executor to update the Airport.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Airport) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	key := makeCacheKey(columns, nil)
	airportUpdateCacheMut.RLock()
	cache, cached := airportUpdateCache[key]
	airportUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			airportAllColumns,
			airportPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update airports, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `airports` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, airportPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(airportType, airportMapping, append(wl, airportPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update airports row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for airports")
	}

	if !cached {
		airportUpdateCacheMut.Lock()
		airportUpdateCache[key] = cache
		airportUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q airportQuery) UpdateAllG(cols M) (int64, error) {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q airportQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for airports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for airports")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AirportSlice) UpdateAllG(cols M) (int64, error) {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AirportSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), airportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `airports` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, airportPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in airport slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all airport")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Airport) UpsertG(updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(boil.GetDB(), updateColumns, insertColumns)
}

var mySQLAirportUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Airport) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no airports provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	nzDefaults := queries.NonZeroDefaultSet(airportColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLAirportUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	airportUpsertCacheMut.RLock()
	cache, cached := airportUpsertCache[key]
	airportUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			airportAllColumns,
			airportColumnsWithDefault,
			airportColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			airportAllColumns,
			airportPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert airports, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "airports", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `airports` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(airportType, airportMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(airportType, airportMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for airports")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == airportMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(airportType, airportMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for airports")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}
	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for airports")
	}

CacheNoHooks:
	if !cached {
		airportUpsertCacheMut.Lock()
		airportUpsertCache[key] = cache
		airportUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single Airport record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Airport) DeleteG() (int64, error) {
	return o.Delete(boil.GetDB())
}

// Delete deletes a single Airport record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Airport) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Airport provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), airportPrimaryKeyMapping)
	sql := "DELETE FROM `airports` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from airports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for airports")
	}

	return rowsAff, nil
}

func (q airportQuery) DeleteAllG() (int64, error) {
	return q.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all matching rows.
func (q airportQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no airportQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from airports")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for airports")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o AirportSlice) DeleteAllG() (int64, error) {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AirportSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), airportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `airports` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, airportPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from airport slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for airports")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Airport) ReloadG() error {
	if o == nil {
		return errors.New("models: no Airport provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Airport) Reload(exec boil.Executor) error {
	ret, err := FindAirport(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AirportSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty AirportSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AirportSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AirportSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), airportPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `airports`.* FROM `airports` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, airportPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AirportSlice")
	}

	*o = slice

	return nil
}

// AirportExistsG checks if the Airport row exists.
func AirportExistsG(iD int) (bool, error) {
	return AirportExists(boil.GetDB(), iD)
}

// AirportExists checks if the Airport row exists.
func AirportExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `airports` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if airports exists")
	}

	return exists, nil
}
